[package]
name = "chain"
version = "0.1.0"
authors = ["Joseph A Mark <sjeohp@gmail.com>"]
license = "MIT"
description = "blockchain generation framework"
repository = "https://github.com/sjeohp/rust-chain.git"
keywords = ["blockchain", "chain", "distributed", "ledger", "cryptocurrency"]

[dependencies]

[lib]
name = "chain"
path = "src/lib.rs"
